### PR TITLE
Add initial support for markdown files with italicization parser

### LINKED ISSUE #8: markdown parser support
I would like to add some support features for .md files. For this, the program will accept .md files, and it will also add italics to the html version for any italicized text in the original text.

### PR DESCRIPTION
**Pull request by cychu42**
# Overview
This pull request is meant to resolve #8. 
The request adds support for markdown files, as well as parser for italicization from markdown input files.

## Features
- Adds support for markdown files conversion to html files.
    - Italicized text in input file will be reflected in the html output file
    - Updated README.md to reflect the support with examples
  
## Code Changes
- Added `isMd` boolean variable as flag for processing `.md` files
- Added code to use `isMd` when a file has the `.md` extension, to process them correctly
- Amended extension checking to include `.md` files for markdown file support
- Changed one error message to include markdown file when user uses a single invalid file as input, to update the message for the new markdown support
- Added code to wrap italicized markdown text (`*text*` or `_text_`) with `<i>` tag when writing output files, to support italicization in markdown files

### CODE REVIEW

**Comment by cychu42** [comment]
Oh, I forgot to revert the split condition back to `"\n\r"`.

**Comment by cychu42** [comment]
OK. I reverted the split condition back to `"\n\r"`. Let me know if you need anything else.

**Comment by alexsam29** [comment]
I have noticed one issue where it doesn't italicize paragraphs or or words with punctuation.

Paragraphs:  
image
image

Punctuation:
image
image

**Comment by alexsam29** [comment]
The paragraph issue might be a bit of a challenge, so a new issue could be created for that.

However the punctuation issue is more within this scope.

**Review by alexsam29 — CHANGES_REQUESTED** [review]
There's a bug where the parser is not italicizing text when there is punctuation after it.  
Ex: ```_Silver Blaze?_```

```index.js``` line 121 and line 126 is the problem.  Something seems to wrong with the regex where it's not catching punctuation.

Try these regex's:  
```/_(.*?)_/```  
```/\*(.*?)\*/```

**Comment by cychu42** [comment]
It seems the issue is the regex not catching certain special characters, so I ended up listing them manually, like: `/_[—!@#$%^&()+;/<>.\s\w\d,?"“”-]+_/`
There's no issue with entire paragraph, it's just certain special characters in a paragraph weren't caught in the previous version.
It should be fine now. If you can, let me know if there's an easier way to do this, instead of listing bunch of special characters.

**sample input:**
image

**sample output:**
image

**Comment by cychu42** [comment]
Oh, reverted split, again. Really have to remember it before I push.

**Review by alexsam29 — APPROVED** [review]
The regex seems to work.  The ideas I had to try and make it simpler didn't work, so this will do for now.

**Pull request merged**
